version: '3.8'

services:
  backend:
    image: python:3.9-slim
    container_name: backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    restart: always
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && 
             uvicorn app.api.api:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    image: python:3.9-slim
    container_name: frontend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - mynetwork
    restart: always
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             streamlit run app/frontend/front.py --server.port 8501 --server.address 0.0.0.0"

networks:
  mynetwork:
    driver: bridge
